kubeslice/kubeslice-cli

cmd/get.go
pkg/project.go

Create, Get, Edit, Describe, Delete actions for Kubeslice CRDs.

Feature crd actions

---

cmd/root.go
pkg/cmd-util.go
pkg/internal/helm-repo-add.go
samples/custom-topology.yaml
samples/kind-demo.yaml

Signed-off-by: Eric Peterson <eric@avesha.io>
Changed the path to the artifacts from...
https://kubeslice.github.io/charts/
...to...
https://kubeslice.github.io/kubeslice/

Changed chart url from charts to kubeslice

---

cmd/root.go

feat(): Added help for root command

---

README.md
cmd/common.go
cmd/edit.go
cmd/get.go
cmd/install.go
cmd/root.go
cmd/uninstall.go
doc/kubeslice-cli.md
doc/kubeslice-cli_create.md
doc/kubeslice-cli_delete.md
doc/kubeslice-cli_describe.md
doc/kubeslice-cli_edit.md
doc/kubeslice-cli_get.md
doc/kubeslice-cli_install.md
doc/kubeslice-cli_register.md
doc/kubeslice-cli_uninstall.md
go.mod
go.sum
pkg/internal/constants.go
pkg/internal/controller.go
pkg/internal/enterprise.go
pkg/internal/project-manifest.go
pkg/internal/worker.go
pkg/slicectl.go
util/executables.go

Enhancement in `uninstall` command to uninstall components using custom topology (`--config` flag). 
- `kubeslice-cli --config <configFile> uninstall` uninstalls all components (controller, worker-registration, slice-operator etc) for the custom topology provided
- Upgraded cobra cli module version to v1.6.1
- Code cleanup and restructure 
Fixes # 
#25 
```release-note
```

feat(#25): Enhancement for uninstall command

---

pkg/internal/worker.go

Fixed an issue which leads to fetching incorrect worker secret.
Fixes #27 
```release-note
```

fix(): incorrect secret fetching fails worker installation

---

cmd/root.go
pkg/internal/cert-manager-setup.go
pkg/slicectl.go

Uninstallation command should also uninstall cert-manager from controller cluster.
Fixes #31 
No
```release-note
```

fix(#31): uninstallation of cert manager

---

cmd/root.go
pkg/internal/kubernetes-operation.go
pkg/internal/worker.go

- Increased wait time for slice-operator installation.
- Added retry logic for fetching secrets.
Fixes # 
```release-note
```

fix(): Increased timeout duration for slice-operator installation

---

pkg/internal/bootstrap-configuration.go
pkg/internal/controller.go
pkg/internal/enterprise.go
pkg/internal/get-network-info.go
pkg/internal/values.go
pkg/internal/verify-executables.go
pkg/internal/worker.go
pkg/slicectl.go
samples/template.yaml
util/print-util.go

- Added support to provide chart values along with custom topology configuration
- Additional support for kind clusters when using custom topology
Fixes :
- Install fails with error deploying Metrics server
- should deploy nodeport service (instead of LB service) and port-forward it
- Message needs to be updated when skipping UI installation 
```release-note
```

feat(): custom helm values

---

pkg/internal/enterprise.go

Fixes # chart version for ui was not being set
[x] Manual testing
```release-note
```

fix(): ui chart version fix

---

cmd/root.go

version update

---

pkg/internal/bootstrap-configuration.go
pkg/internal/project-manifest.go
samples/template.yaml

Fixes #44 
```release-note
```

feat(#44): configure project users

---

.github/workflows/binary-releaser.yaml

ci(): updating token name

---

pkg/internal/print-next-steps.go
pkg/slicectl.go

- iperf application installation with `enterprise-demo` profile
Fixes # 
```release-note
```

fix(): added iperf app in ent-demo

---

cmd/root.go
pkg/cmd-util.go

- Added staging helm charts repo url for enterprise demo.
- 
```release-note
```

fix(): add staging charts

---

pkg/internal/constants.go
pkg/internal/controller.go
pkg/internal/kubernetes-operation.go

- For enterprise demo, verify license creation after controller installation.
```console
kubeslice-cli install -p enterprise-demo
...
♻ Waiting for KubeSlice Controller Pods to be Healthy... 95 seconds elapsed
♻ Waiting for KubeSlice Trial License to be Ready...
✔ Successfully installed KubeSlice Controller.
```
```release-note
```

fix(): license secret pre-check

---

pkg/internal/generate-kind-templates.go

- Updated k8s node image in Kind configurations to `v1.25.11`
Fixes # 
```release-note
```

fix(): update kindest images

---

cmd/root.go
pkg/internal/constants.go
pkg/internal/controller.go
pkg/internal/generate-kind-templates.go
pkg/internal/kubernetes-operation.go

- fix(): update kindest images
- fix(): license secret pre-check
```release-note
```

fix(): v0.5.4

---

AUTHORS
CONTRIBUTING.md
MAINTAINERS.md
code_of_conduct.md

doc(): adding contributing guide and code of conduct

---

code_of_conduct.md

doc(): broken link fix

---

SECURITY.md

Added SECURITY.md file to the repository to provide guidelines and procedures for reporting security vulnerabilities. This file outlines how security issues should be reported and handled within the project.
No explicit tests are needed for this change. The file addition is tested implicitly by ensuring it appears in the repository structure.
```release-note
```

docs(): add security policy for kubeslice-cli

---

pkg/internal/bootstrap-configuration.go
pkg/internal/helm-repo-add.go

feat(): use local charts
